server:
  port: 8000

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: dev
    password: 12345678
    hikari:
      connection-test-query: select user();

kafka:
  bootstrap-servers: 127.0.0.1:9092
  producer:
    topic-name: transaction

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: INFO
