server:
  port: 8000

spring:
  application:
    name: demo
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

kafka:
  bootstrap-servers: 127.0.0.1:9092
  producer:
    topics:
      transfer
    partitions: 5
