
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: dev
    password: 12345678
    hikari:
      connection-test-query: select user();

mybatis:
  type-aliases-package: com.demo.common.entity
  mapper-locations: classpath:mybatis/mappers/*.xml

